### ISSUE TITLE
Remove a full line on MacOS

### ISSUE THREAD

**Issue by Tomdazy** [malt03/annay#6]
Hello, when on MacOS, we use the shortcut to remove a line (cmd + <- ) it removes the note, would it be possible to, when you are editing, only remove the current line like it does on Mac and to remove the note when we have select it ?
Thanks ;)

**Comment by malt03** [comment]
@Tomdazy Sorry for terrible late reply.
I fixed this with version 1.2.1 that is on review.
Thank you for your issue.
